# Generated by Django 5.1.6 on 2025-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdzanSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='adzan_sounds/')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalSalat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100, unique=True)),
                ('tanggal', models.DateField()),
                ('imsak', models.TimeField()),
                ('subuh', models.TimeField()),
                ('dzuhur', models.TimeField()),
                ('ashar', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isya', models.TimeField()),
            ],
        ),
    ]
